VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "estFlujosDeuda"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public tipopos As Integer
Public fechareg As Date
Public nompos As String
Public horareg As String
Public coperacion As String
Public tpata As String
Public finicio As Date
Public ffin As Date
Public fpago As Date
Public saldo As Double
Public amort As Double
Public pago_int As String
Public int_t_saldo As String
Public t_cupon As Double

