VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ParamValPos"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public indpos As Long
Public siPLimpio As Boolean
Public sicalcdv01 As Boolean
Public sicalcdur As Boolean
Public sicalcdurM As Boolean
Public sicalcVE As Boolean
Public sicalcPE As Boolean
Public simostrarap As Boolean
Public tModCurva As Integer
Public siValExc As Boolean
Public perfwd As Long
Public siTCambio As Boolean
Public mVBondesD As Integer
Public msgSist As String
Public si_int_flujos As Boolean

