VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "paramValFlujo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
 
 Public intInFlujos As String
 Public intFinFlujos As String
 Public convInt As String
 Public pcref As Integer
 Public inFLujo As Long
 Public finFLujo As Long
 Public perfwd As Long
 Public sobret As Double
 Public acumInt As String
 Public modint1 As Integer
 Public modint2 As Integer
 Public tCambio As Double
 Public sicalcVE As Boolean
