VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "propVecPrecios"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False


Public fecha As Date
Public psucio As Double
Public plimpio As Double
Public tmercado As String
Public tv As String
Public emision As String
Public serie As String
Public vnominal As String
Public c_emision As String
Public dxv As Long
Public st_colocacion As Double
Public tasa_st As Double

Public tcupon As Double
Public pcupon As Integer
Public femision As Date
Public fvenc As Date
Public isin As String

Public yield As Double
Public calif_sp As String
Public calif_fitch As String
Public calif_moodys As String
Public calif_hr As String
Public calif_verum As String
Public regla_cupon As String
Public frec_cupon As String
Public monto_em As Double
Public monto_cir As Double
Public moneda As Integer
Public int_md As Double


