VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "PropSwap"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
   Public c_oper As String
   Public f_i_swap As Date
   Public f_v_swap As Date
   Public int_noc_i As String
   Public int_noc_f As String
   Public cap_int_activa As String
   Public cap_int_pasiva As String
   Public tr_activa As String
   Public tr_pasiva As String
   Public st_activa As Double
   Public st_pasiva As Double
   Public conv_int_act As String
   Public conv_int_pas As String
   
   
