VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "propRelSwapPrim"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

'propRelSwapPrim

Public coperacion  As String
Public finicio As Date
Public ffin As Date
Public c_ppactiva As String
Public c_pppasiva As String
Public c_pswap As String
Public t_efect As Integer
