VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "resCVA"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public descrip As String
Public escala As String
Public calif As String
Public mtm As Double
Public cvaderiv As Double
Public cvamd As Double
Public cvapidv As Double
Public cvapicv As Double
Public cvatotal As Double
Public cvat_1 As Double
Public cva_dif As Double


