VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "resEficSwap"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public v_swapact As Double
Public v_swappas As Double
Public v_primact As Double
Public v_primpas As Double
Public id_swapact As Double
Public id_swappas As Double
Public id_primact As Double
Public id_primpas As Double
Public var_swap_act As Double
Public var_swap_pas As Double
Public var_pp_act As Double
Public var_pp_pas As Double
Public val_efect As Double
