VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ResEfRetroSwap"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public c_operacion As String
Public t_efectividad As Integer
Public v_swap_act_0 As Double
Public v_swap_pas_0 As Double
Public v_pp_act_0 As Double
Public v_pp_pas_0 As Double


Public v_swap_act_1 As Double
Public v_swap_pas_1 As Double
Public v_pp_act_1 As Double
Public v_pp_pas_1 As Double

Public var_swap_act As Double
Public var_swap_pas As Double

Public var_pp_act As Double
Public var_pp_pas As Double


