VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "resValIns"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public mtm_sucio As Double
Public mtm_ve_sucio As Double
Public mtm_limpio As Double
Public ps_activa As Double
Public ps_pasiva As Double
Public pl_activa As Double
Public pl_pasiva As Double
Public intdevact As Double
Public intdevpas As Double
Public pu_sucio As Double
Public p_esperada As Double
Public pu_ve As Double
Public pu_limpio As Double
Public duractiva As Double
Public durpasiva As Double
Public duractM As Double
Public durpasM As Double
Public dv01activa As Double
Public dv01pasiva As Double
Public valVEact As Double
Public valVEpas As Double
